name: Update sources
on: [pull_request]

jobs:
  update-sources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - uses: mikefarah/yq@master
        id: manifestTagVersion
        with:
          cmd: yq '.modules[0].sources[1].tag' 'io.github.hrkfdn.ncspot.yml'
      
      - uses: actions/checkout@v3
        with:
          path: ncspot
          repository: hrkfdn/ncspot
          ref: ${{ steps.manifestTagVersion.outputs.result }}
      
      - name: Update cargo-sources.json
        run: |
          apt update -y && install -y python3-aiohttp python3-toml
          python3 flatpak-builder-tools/cargo/flatpak-cargo-generator.py -o cargo-sources.json ncspot/Cargo.lock
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add cargo-sources.json
          git commit -m 'Update cargo-sources.json'
          git push
